### PR TITLE
fix(sync-service): Start up with empty state when shape db file corrupted

### LINKED ISSUE #3832: sync-service: invalid shape db crashes entire app
https://discord.com/channels/933657521581858818/933657523049885698/1471177680488628306

```
Kernel pid terminated (application_controller) ("{application_start_failure,electric,{{shutdown,{failed_to_start_child,'Elixir.Electric.StackSupervisor',{shutdown,{failed_to_start_child,'Elixir.Electric.MonitoredCoreSupervisor',{shutdown,{failed_to_start_child,'Elixir.Electric.ShapeCache.ShapeStatus.ShapeDb.Supervisor',{shutdown,{failed_to_start_child,'Elixir.Electric.ShapeCache.ShapeStatus.ShapeDb.Migrator',<<\"file is not a database\">>}}}}}}}},{'Elixir.Electric.Application',start,[normal,[]]}}}")
```

Database file is totally invalid, not subtly corrupted but completely *not* a sqlite db file -- it's missing the default header.

We should recover from a situation like this by deleting the corrupt file and starting from scratch

### PR DESCRIPTION
**Pull request by magnetised**
If the shape database file has been corrupted, the system current fails to start. This PR catches that situation and recovers by deleting the corrupt database file and starting anew. 

Fixes #3832

### CODE REVIEW

File: packages/sync-service/lib/electric/shape_cache/shape_status/shape_db/connection.ex [hunk 1]
```diff
@@ -170,13 +186,56 @@ defmodule Electric.ShapeCache.ShapeStatus.ShapeDb.Connection do
     {:ok, client_state, pool_state}
   end
 
-  def open(pool_state) do
+  def open(pool_state, opts \\ []) do
     with {:ok, db_path} <- db_path(pool_state),
-         {:ok, conn} <- Sqlite3.open(db_path, open_opts(pool_state)) do
+         {:ok, conn} <- open_with_recovery(db_path, pool_state, opts, 2) do
```
Comment (alco) [inline packages/sync-service/lib/electric/shape_cache/shape_status/shape_db/connection.ex]: Please define `@max_recovery_attempts`.

**Review by alco — APPROVED** [review]
:+1:
