### PR TITLE
fix: account for hash collisions in across shape definitions

### LINKED ISSUE #2778: Shape hash collisions shouldn't yield same shape handle
**Versions**
- Electric: 1.0.16 & earlier

**Bug description**
When 2 shapes have the same hash, they resolve to the same (cached) shape handle.

**Expected behavior**
We must never return same shape handle for different shapes, as that leads to data from another shape being shown.

### PR DESCRIPTION
**Pull request by icehaunter**
Closes #2778

### CODE REVIEW

**Comment by icehaunter** [comment]
Benchmark this

**Review by alco — APPROVED** [review]

File: packages/sync-service/lib/electric/shape_cache/shape_status.ex [hunk 1]
```diff
@@ -322,11 +322,10 @@ defmodule Electric.ShapeCache.ShapeStatus do
         state.shape_meta_table,
         Enum.concat([
           Enum.flat_map(shapes, fn {shape_handle, shape} ->
-            hash = Shape.hash(shape)
             relations = Shape.list_relations(shape)
 
             [
-              {{@shape_hash_lookup, hash}, shape_handle},
+              {{@shape_hash_lookup, Shape.comparable(shape)}, shape_handle},
```
Comment (msfstef) [inline packages/sync-service/lib/electric/shape_cache/shape_status.ex:328]: does this have a significant memory and/or performance impact? We are now keeping the whole shape as a key, and I don't know if it also impacts lookup performance in ETS in any way?

File: packages/sync-service/lib/electric/shape_cache/shape_status.ex [hunk 2]
```diff
@@ -103,7 +103,7 @@ defmodule Electric.ShapeCache.ShapeStatus do
       :ets.insert_new(
         state.shape_meta_table,
         [
-          {{@shape_hash_lookup, hash}, shape_handle},
+          {{@shape_hash_lookup, Shape.comparable(shape)}, shape_handle},
```
Comment (msfstef) [inline packages/sync-service/lib/electric/shape_cache/shape_status.ex:106]: nit: can you add this to `remove_shape` to avoid walking the table as well as part of this? (the `:ets.select_delete` call)

**Review by msfstef — APPROVED** [review]
Looks good! This looks backwards compatible, but just to double check would previous shape handles be untouched and can be maintained as they are (from disk)?
