### PR TITLE
Fix transaction filtering by taking into account snapshot's xmax and xip_list

### LINKED ISSUE #2313: Store the complete PG snapshot info on shape snapshots to filter all repeat transactions
@samwillis has had a brilliant insight:

We currently filter transactions incoming on the replication stream based on the snapshot's `xmin`. We need to (also) use `xmax` and `xip_list` to filter correctly. All three values are returned by PG's [`pg_current_snapshot()`](https://www.postgresql.org/docs/current/functions-info.html#FUNCTIONS-PG-SNAPSHOT) function.

xmin is the lowest active transaction ID, there can be txids > xmin that have committed and so would appear in the snapshot. This, with our buffering of the replocation stream before fetfhing the snapshot, results in a condition where we can potentually have duplicate inserts between the snapshot and the shape log.

Image

The current filtering logic should be corrected by an additional clause: any transaction coming from the replication stream for which `xmin < xid and xid < xmax and xid not in xip_list` needs to be skipped. In pseudocode form:

```
# Transaction already part of the snapshot because it had committed before
# we started taking the snapshot.
defp handle_txn(%Transaction{xid: xid}, %{snapshot_xmin: xmin})
  when xid < xmin,
  do: <skip txn>

# Transaction commited sometime between xmin and the moment when we started
# taking the snapshot.
defp handle_txn(%Transaction{xid: xid}, %{snapshot_xmax: xmax, snapshot_xip_list: xip_list})
  when xid < xmax and xid not in xip_list,
  do: <skip txn>

# Transaction was either active at the time of taking the snapshot:
#   xid == xmin or xid in xip_list
# OR
# it committed after the snapshot had completed:
#   xid >= xmax
defp handle_txn(%Transaction{xid: xid}, _),
  do: <add txn to the log>
```

Once we have stored in the log the first transaction whose `xid` ≥ `xmax`, we can mark the snapshot such that the comparisons can be skipped for all future transactions. At this point, we are sure that any new transaction arriving on the replication stream is not part of the snapshot.

Skipping further comparisons will absolve us of the need to worry about the number of wraparounds of 32-bit transaction IDs.

### PR DESCRIPTION
**Pull request by alco**
Electric now stores the full pg snapshot info in the shape snapshot. Transaction filtering logic is then improved to skip additional transactions that are already included in the snapshot.

This change is backwards-compatible with existing shapes.

Fixes #2313.

### CODE REVIEW

File: packages/sync-service/lib/pg_interop/postgrex/extensions/pg_snapshot.ex [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+  use Postgrex.BinaryExtension, send: "pg_snapshot_send"
+  import Postgrex.BinaryUtils, warn: false
+
+  def encode(_state) do
+    quote location: :keep do
+      _ -> raise DBConnection.EncodeError, "encoding of type pg_snapshot not implemented"
+    end
+  end
+
+  def decode(_) do
```
Comment (msfstef) [inline packages/sync-service/lib/pg_interop/postgrex/extensions/pg_snapshot.ex:11]: should we have some basic tests for this?

File: packages/sync-service/lib/electric/shapes/consumer.ex [hunk 2]
```diff
@@ -241,20 +254,53 @@ defmodule Electric.Shapes.Consumer do
...
-        [xid: txn.xid, total_num_changes: txn.num_changes] ++
-          shape_attrs(state.shape_handle, state.shape)
+  defp handle_txn(txn, %{pg_snapshot: %{filter_txns?: false}} = state) do
+    handle_txn_in_span(txn, state)
+  end
 
-      OpenTelemetry.with_span("shape_write.consumer.handle_txn", ot_attrs, state.stack_id, fn ->
-        do_handle_txn(txn, state)
-      end)
+  defp handle_txn(
```
Comment (msfstef) [inline packages/sync-service/lib/electric/shapes/consumer.ex:261]: very nice comments! should we potentially leave a link to [PG docs](https://www.postgresql.org/docs/current/functions-info.html#FUNCTIONS-PG-SNAPSHOT-PARTS) about this as well? and do our tests cover some or all of these cases?

**Review by msfstef — APPROVED** [review]
Nice work!

File: packages/sync-service/lib/pg_interop/postgrex/extensions/pg_snapshot.ex (hunk 1 above)
Comment (alco) [reply packages/sync-service/lib/pg_interop/postgrex/extensions/pg_snapshot.ex:11]: Yes! I've added one for encode and one for decode.

File: packages/sync-service/lib/electric/shapes/consumer.ex (hunk 2 above)
Comment (alco) [reply packages/sync-service/lib/electric/shapes/consumer.ex:261]: Not right now. Tricky to test, will think of something. Filed as https://github.com/electric-sql/electric/issues/2311?issue=electric-sql%7Celectric%7C2348

**Review by msfstef — APPROVED** [review]
