### PR TITLE
Fix decoding of TRUNCATE message options

### LINKED ISSUE #2855: ReplicationClient no case clause matching: 3
**Versions**
- Elixir/OTP 27
- Electric: :embedded through Phoenix Sync 

**Bug description**
Using Phoenix Sync:
1. Populate a table with some rows
2. Sync a shape to the client
3. On the backend, truncate the table with cascade and restart identity
4. Note syncing breaks, and the following error is shown in iex:
```iex
[error] :gen_statem {:"Electric.ProcessRegistry:electric-embedded", {Electric.Postgres.ReplicationClient, nil}} terminating
** (CaseClauseError) no case clause matching: 3
    (electric 1.0.20) lib/electric/postgres/logical_replication/decoder.ex:194: Electric.Postgres.LogicalReplication.Decoder.decode_message_impl/1
    (stdlib 6.2.2) timer.erl:595: :timer.tc/2
    (electric 1.0.20) lib/electric/telemetry/open_telemetry.ex:98: Electric.Telemetry.OpenTelemetry.timed_fun/3
    (electric 1.0.20) lib/electric/postgres/replication_client.ex:272: Electric.Postgres.ReplicationClient.process_x_log_data/3
    (opentelemetry_api 1.4.0) src/otel_tracer_noop.erl:59: :otel_tracer_noop.with_span/5
    (electric 1.0.20) lib/electric/telemetry/open_telemetry.ex:87: anonymous fn/3 in Electric.Telemetry.OpenTelemetry.do_with_span/4
    (telemetry 1.3.0) /Users/paul/hello-app/elixir/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
    (postgrex 0.20.0) lib/postgrex/replication_connection.ex:561: Postgrex.ReplicationConnection.handle/5
    (postgrex 0.20.0) lib/postgrex/replication_connection.ex:547: Postgrex.ReplicationConnection.handle_data/2
    (stdlib 6.2.2) gen_statem.erl:3737: :gen_statem.loop_state_callback/11
    (stdlib 6.2.2) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
Process Label: {:replication_client, "electric-embedded"}
Queue: [info: {:tcp, #Port<0.79>, <<100, 0, 0, 0, 156, 119, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 219, 126, 58, 99, 191, 144, 82, 0, 0, 64, 167, 112, 117, 98, 108, 105, 99, 0, 109, 101, 115, 115, ...>>}]
Postponed: []
State: {:no_state, %Postgrex.ReplicationConnection{protocol: %Postgrex.Protocol{sock: {:gen_tcp, #Port<0.79>}, connection_id: 1126, connection_key: -204470574, peer: {{127, 0, 0, 1}, 5432}, types: {Postgrex.DefaultTypes, #Reference<0.1896195449.1765670913.74319>}, null: nil, timeout: 15000, ping_timeout: 15000, parameters: #Reference<0.1896195449.1765539841.80885>, queries: #Reference<0.1896195449.1765670913.80884>, postgres: :idle, transactions: :naive, buffer: :active_once, disconnect_on_error_codes: [], scram: %{auth_message: "n=,r=NLMTI8801gV0n6HthdJgEGNb,r=NLMTI8801gV0n6HthdJgEGNb7RywadH2VYRoVndLZXeOQUbu,s=4Jyt7+7C76LFqy2xOzlu2A==,i=4096,c=biws,r=NLMTI8801gV0n6HthdJgEGNb7RywadH2VYRoVndLZXeOQUbu", iterations: 4096, salt: <<224, 156, 173, 239, 238, 194, 239, 162, 197, 171, 45, 177, 59, 57, 110, 216>>}, disable_composite_types: false, messages: []}, state: {Electric.Postgres.ReplicationClient, %Electric.Postgres.ReplicationClient.State{stack_id: "electric-embedded", connection_manager: #PID<0.488.0>, transaction_received: {Electric.Replication.ShapeLogCollector, :store_transaction, [{:via, Registry, {:"Electric.ProcessRegistry:electric-embedded", {Electric.Replication.ShapeLogCollector, nil}}}]}, relation_received: {Electric.Replication.ShapeLogCollector, :handle_relation_msg, [{:via, Registry, {:"Electric.ProcessRegistry:electric-embedded", {Electric.Replication.ShapeLogCollector, nil}}}]}, publication_name: "electric_publication_default", try_creating_publication?: true, recreate_slot?: nil, start_streaming?: false, slot_name: "electric_slot_default", slot_temporary?: false, display_settings: [], origin: "postgres", txn_collector: %Electric.Postgres.ReplicationClient.Collector{transaction: %Electric.Replication.Changes.Transaction{xid: 788, commit_timestamp: ~U[2025-06-26 19:45:38.048499Z], lsn: #Lsn<0/261EE38>, last_log_offset: nil, changes: [], num_changes: 0, affected_relations: MapSet.new([])}, tx_op_index: 0, relations: %{16535 => %Electric.Postgres.LogicalReplication.Messages.Relation{id: 16535, namespace: "public", name: "room", replica_identity: :all_columns, columns: [%Electric.Postgres.LogicalReplication.Messages.Relation.Column{flags: [:key], name: "id", type_oid: 2950, type_modifier: -1}, %Electric.Postgres.LogicalReplication.Messages.Relation.Column{flags: [:key], name: "title", type_oid: 1043, type_modifier: 259}, %Electric.Postgres.LogicalReplication.Messages.Relation.Column{flags: [:key], name: "inserted_at", type_oid: 1114, type_modifier: 0}, %Electric.Postgres.LogicalReplication.Messages.Relation.Column{flags: [:key], name: "updated_at", type_oid: 1114, type_modifier: 0}]}}}, step: :streaming, applied_wal: 0}}, auto_reconnect: false, reconnect_backoff: 500, streaming: 500}}
Callback mode: :handle_event_function, state_enter: false
[error] Electric.DBConnection unknown error: {:case_clause, 3}
[warning] Database connection in replication mode failed: {:case_clause, 3}
Retrying...
[warning] Reconnecting in 10000ms
```
**Other findings**
This seems to survive a truncation *without* the "restart identity", but I'd like to include it if possible. I'm also assuming that the typescript client supports truncation, so that the client can clear out it's view of the query and start fresh. Is this the case?

### PR DESCRIPTION
**Pull request by alco**
Fix #2855.

### CODE REVIEW

File: packages/sync-service/lib/electric/postgres/logical_replication/decoder.ex [hunk 1]
```diff
@@ -274,4 +271,14 @@ defmodule Electric.Postgres.LogicalReplication.Decoder do
...
+
+  defp decode_bitflags(bitfield, flag_defs) do
+    Enum.reduce(flag_defs, [], fn {flag_pos, flag_val}, acc ->
+      if band(bitfield, 1 <<< flag_pos) > 0 do
+        [flag_val | acc]
+      else
+        acc
+      end
+    end)
+  end
```
Comment (robacourt) [inline packages/sync-service/lib/electric/postgres/logical_replication/decoder.ex]: I'm guessing this could be done with binary pattern matching, something like:

```elixir
defp decode_options(<<restart_identity::1, cascade::1, _::binary>>) do
  %{restart_identity: restart_identity == 1, cascade: cascade == 1}
 end
```

I'd probably find it easier to read and reason about if there was an issue

**Review by robacourt — APPROVED** [review]
Nice one! I just left a little nit

File: packages/sync-service/lib/electric/postgres/logical_replication/decoder.ex (hunk 1 above)
Comment (alco) [reply packages/sync-service/lib/electric/postgres/logical_replication/decoder.ex]: Right! How did I not think of that?

Though I don't want to change the type of the return value, it's going to remain a list of atoms.
