### PR TITLE
Return 409 immediately to live requests when shape invalidated

### LINKED ISSUE #2585: A live shape request doesn't get interrupted by shape invalidation
**Versions**

Reproducible on the latest [`main`](https://github.com/electric-sql/electric/commit/ed165ec9e0a716a49de1970efcfa443333521300) version of the server.

**Bug description**

It is a minor bug.

Create a table with one row in it, create a shape and start a live request for it:
```
=# CREATE TABLE test(payload jsonb, id uuid primary key);
CREATE TABLE

=# INSERT INTO test(payload, id)
     SELECT ('{"id": "' || id || '", "description": "..."}')::json, id FROM gen_random_uuid() id;
INSERT 0 1

$ curl -i http://localhost:3000/v1/shape\?offset=-1&table=test
HTTP/1.1 200 OK
electric-server: ElectricSQL/1.0.5
electric-handle: 109192296-1744370730054
electric-schema: {"id":{"type":"uuid","not_null":true,"pk_index":0},"payload":{"type":"jsonb"}}
electric-offset: 0_0

[{"key":"\"public\".\"test\"/\"feb3925b-143a-4f44-9fcb-89eeb864f4d1\"","value":{"id":"feb3925b-143a-4f44-9fcb-89eeb864f4d1","payload":"{\"id\": \"feb3925b-143a-4f44-9fcb-89eeb864f4d1\", \"description\": \"...\"}"},"headers":{"operation":"insert","relation":["public","test"]}}

$ curl -i http://localhost:3000/v1/shape\?offset=0_0&table=test&handle=109192296-1744370730054&live=true
```

While the live request is waiting for data, alter the table schema and insert a new row:
```
=# alter table test drop column id;
ALTER TABLE

=# INSERT INTO test(payload)
     SELECT ('{"id": "' || id || '", "description": "..."}')::json FROM gen_random_uuid() id;
INSERT 0 1
```

The Electric server detects the schema change and invalidates the shape. However, the live request doesn't get interrupted and returns an `up-to-date` response after the long-poll timeout is reached:
```
# $ curl -i http://localhost:3000/v1/shape\?offset=0_0&table=test&handle=109192296-1744370730054&live=true
HTTP/1.1 200 OK
electric-server: ElectricSQL/1.0.5
electric-cursor: 15938780
electric-handle: 109192296-1744370730054
electric-up-to-date: 
electric-offset: 0_inf

[{"headers":{"control":"up-to-date","global_last_seen_lsn":"0"}}]
```

Only the subsequent request using the same shape handle returns a `must-refetch` response:
```
$ curl -i http://localhost:3000/v1/shape\?offset=0_inf&table=test&handle=109192296-1744370730054&live=true
HTTP/1.1 409 Conflict
electric-server: ElectricSQL/1.0.5
location: /v1/shape?handle=105980062-1744370777033&offset=-1&table=test
electric-handle: 105980062-1744370777033
electric-schema: {"payload":{"type":"jsonb"}}

[{"headers":{"control":"must-refetch"}}]
```

**Expected behavior**

While the bug is minor and shape data streaming is healed after the client retries the live request using the new URL from the `location` header, there is a delay between the table in the database getting a new row inserted and the client receiving it, which can be as long as the full duration of a single live request.

### PR DESCRIPTION
**Pull request by magnetised**
There's no need to reply with a 200 and then require a second request to get the 409 status. we can just send the 409 immediately and save a round-trip. the two are functionally identical - a live request returns a 409, only the duration of that request changes.

Fixes #2585

### CODE REVIEW

File: packages/sync-service/timeout.exs [hunk 1]
```diff
@@ -0,0 +1,57 @@
+defmodule W do
```
Comment (alco) [inline packages/sync-service/timeout.exs:1]: Did you commit this by mistake? Otherwise, a moduledoc would be useful to have here.

File: packages/sync-service/lib/electric/shapes/consumer.ex [hunk 2]
```diff
@@ -216,12 +216,10 @@ defmodule Electric.Shapes.Consumer do
...
     state =
-      reply_to_snapshot_waiters(
-        {:error, "Shape relation changed before snapshot was ready"},
-        state
-      )
-
-    cleanup(state)
+      state
+      |> reply_to_snapshot_waiters({:error, "Shape relation changed before snapshot was ready"})
+      |> notify_shape_rotation()
```
Comment (alco) [inline packages/sync-service/lib/electric/shapes/consumer.ex:221]: Was this the missing piece without which the live request would wait until the timeout runs out before returning a response?

File: packages/elixir-client/set_dependency_version.ex [hunk 3]
```diff
@@ -0,0 +1,61 @@
+Mix.install([{:sourceror, "~> 1.7"}, {:jason, "~> 1.4"}])
```
Comment (alco) [inline packages/elixir-client/set_dependency_version.ex:1]: This change doesn't seem to belong in this PR.

**Review by alco — APPROVED** [review]
:speedboat:

**Review by msfstef — APPROVED** [review]
Looks good! Just +1-ing @alco 's comments mostly

File: packages/sync-service/timeout.exs (hunk 1 above)
Comment (magnetised) [reply packages/sync-service/timeout.exs:1]: oops!

File: packages/sync-service/lib/electric/shapes/consumer.ex (hunk 2 above)
Comment (magnetised) [reply packages/sync-service/lib/electric/shapes/consumer.ex:221]: yes, that's all it was

File: packages/elixir-client/set_dependency_version.ex (hunk 3 above)
Comment (magnetised) [reply packages/elixir-client/set_dependency_version.ex:1]: i seem to have been a bit heavy-handed with my "add to commit" flow
