### PR TITLE
fix: ensure materializer starting after consumer died doesn't log an error

### LINKED ISSUE #3657: Subqueries error: Shape terminated before snapshot was ready
Sentry Issue: [ELECTRIC-5C3](https://electricsql-04.sentry.io/issues/84073404/?referrer=github_integration)

```
GenServer {"XXX", "89945450-1767015503383672"} terminating
** (stop) exited in: GenServer.call({:via, Registry, {:"Electric.ProcessRegistry:XXX", {Electric.Shapes.Consumer.Materializer, "72243301-1767015503383298"}}}, :subscribe, 5000)
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, "Shape terminated before snapshot was ready"}
            (electric 1.2.9) lib/electric/shapes/consumer/materializer.ex:111: Electric.Shapes.Consumer.Materializer.handle_continue/2
            (stdlib 7.0.2) gen_server.erl:2424: :gen_server.try_handle_continue/3
            (stdlib 7.0.2) gen_server.erl:2291: :gen_server.loop/4
            (stdlib 7.0.2) proc_lib.erl:333: :proc_lib.init_p_do_apply/3
    (elixir 1.18.4) lib/gen_server.ex:1128: GenServer.call/3
    (electric 1.2.9) lib/electric/shapes/consumer.ex:723: anonymous fn/2 in Electric.Shapes.Consumer.all_materializers_alive?/1
    (elixir 1.18.4) lib/enum.ex:4315: Enum.predicate_list/3
    (electric 1.2.9) lib/electric/shapes/consumer.ex:138: Electric.Shapes.Consumer.handle_continue/2
    (stdlib 7.0.2) gen_server.erl:2424: :gen_server.try_handle_continue/3
    (stdlib 7.0.2) gen_server.erl:2291: :gen_server.loop/4
    (stdlib 7.0.2) proc_lib.erl:333: :proc_lib.init_p_do_apply/3
Process Label: {:consumer, "89945450-1767015503383672"}
Last message: {:continue, {:init_consumer, :create, %{:"$__otel_baggage_ctx_key" => %{"stack_id" => {"XXX", []}}, {:otel_tracer, :span_ctx} => {:span_ctx, 273830246638467783058829103994835601643, "ce01c983d7826d9aa30b4d75011088eb", 13982328423388107469, "c20b359e98e552cd", 0, {:tracestate, []}, true, true, false, {:otel_span_ets, #Function<2.22926739/1 in :otel_tracer_server.on_end/1>}}}}}
```

### PR DESCRIPTION
**Pull request by icehaunter**
Closes #3657

### CODE REVIEW

File: packages/sync-service/lib/electric/shapes/consumer/materializer.ex [hunk 1]
```diff
@@ -108,15 +108,19 @@ defmodule Electric.Shapes.Consumer.Materializer do
     stack_storage = Storage.for_stack(stack_id)
     shape_storage = Storage.for_shape(shape_handle, stack_storage)
 
-    :started = Consumer.await_snapshot_start(stack_id, shape_handle, :infinity)
+    case Consumer.await_snapshot_start(stack_id, shape_handle, :infinity) do
+      :started ->
+        Consumer.subscribe_materializer(stack_id, shape_handle, self())
```
Comment (msfstef) [inline packages/sync-service/lib/electric/shapes/consumer/materializer.ex:113]: can't `subscribe_materializer` also fail? had opened a claude concurrency issue draft PR with this https://github.com/electric-sql/electric/pull/3721
