### PR TITLE
Proper error handling when Electric doesn't have read permissions for user tables

### LINKED ISSUE #2948: Failure trying to create a shape for a table which Electric cannot SELECT from
When a new shape request is processed for a table for which Electric doesn't have the read permission, the snapshotter process emits the `:snapshot_started` notification before actually starting to read from the database. The shape consumer then incorrectly thinks that it can serve snapshot chunks in response to the client request even though no chunk files have been created on disk.

The request-serving process in Electric ends up crashing with an :enoent error:
    
    [error] ** (Electric.ShapeCache.Storage.Error) failed to open ./persistent/shapes/single_stack/48297321-1754091527499338/log/0.jsonsnapshot: :enoent
      (electric 1.1.0) lib/electric/shape_cache/pure_file_storage/snapshot.ex:142: Electric.ShapeCache.PureFileStorage.Snapshot.wait_and_open!/3
      (electric 1.1.0) lib/electric/shape_cache/pure_file_storage/snapshot.ex:94: anonymous fn/1 in Electric.ShapeCache.PureFileStorage.Snapshot.stream_chunk_lines/2
      (elixir 1.18.4) lib/stream.ex:1557: anonymous fn/5 in Stream.resource/3
      (elixir 1.18.4) lib/stream.ex:1066: Stream.do_transform_inner_enum/7
      (elixir 1.18.4) lib/stream.ex:1773: Enumerable.Stream.do_each/4
      (elixir 1.18.4) lib/stream.ex:956: Stream.do_transform/5
      (elixir 1.18.4) lib/stream.ex:1066: Stream.do_transform_inner_enum/7
      (elixir 1.18.4) lib/stream.ex:1773: Enumerable.Stream.do_each/4
      (elixir 1.18.4) lib/stream.ex:956: Stream.do_transform/5
      (elixir 1.18.4) lib/enum.ex:2600: Enum.reduce_while/3
      (electric 1.1.0) lib/electric/shapes/api/response.ex:390: Electric.Shapes.Api.Response.send_stream/2
      (electric 1.1.0) lib/electric/plug/serve_shape_plug.ex:1: Electric.Plug.ServeShapePlug.plug_builder_call/2
      [...]
    
and the client connection is closed abruptly:
    
    $ curl -i http://localhost:3000/v1/shape\?table=items&offset=-1
    HTTP/1.1 200 OK
    transfer-encoding: chunked
    date: Fri, 01 Aug 2025 23:36:37 GMT
    vary: accept-encoding
    cache-control: public, max-age=604800, s-maxage=3600, stale-while-revalidate=2629746
    x-request-id: GFfI1SBxQHqWR_EAACYD
    electric-server: ElectricSQL/1.1.0
    access-control-allow-origin: *
    access-control-expose-headers: electric-cursor,electric-handle,electric-offset,electric-schema,electric-up-to-date,electric-internal-known-error
    access-control-allow-methods: GET, HEAD, DELETE, OPTIONS
    content-type: application/json; charset=utf-8
    etag: "48297321-1754091397708704:-1:0_0"
    electric-handle: 48297321-1754091397708704
    electric-schema: {"val":{"type":"text"}}
    electric-offset: 0_0
    
    curl: (18) transfer closed with outstanding read data remaining

### PR DESCRIPTION
**Pull request by alco**
Fixes #2948.

### CODE REVIEW

**Comment by alco** [comment]
Added a unit test as well to cover this error.

If I revert the fix commit and run the unit test, it fails with the following output:
```
  1) test /v1/shapes with manual publication management GET fails to create initial snapshot when Electric cannot read from the table (Electric.Plug.LowPrivilegeRouterTest)
     test/electric/plug/low_privilege_router_test.exs:47
     ** (Plug.Conn.WrapperError) ** (Electric.ShapeCache.Storage.Error) failed to open /home/alco/code/electric-sql/electric/packages/sync-service/tmp/Electric.Plug.LowPrivilegeRouterTest/test--v1-shapes-with-manual-publication-management-GET-fails-to-create-initial-snapshot-when-Electric-cannot-read-from-the-table-66ae8f64/Electric.Plug.LowPrivilegeRouterTest test /v1/shapes with manual publication management GET fails to create initial snapshot when Electric cannot read from the table/129372036-1754867607785384/log/0.jsonsnapshot: :enoent
     code: get_shape(ctx)
     stacktrace:
       (electric 1.1.0) lib/electric/shape_cache/pure_file_storage/snapshot.ex:139: Electric.ShapeCache.PureFileStorage.Snapshot.wait_and_open!/3
       (electric 1.1.0) lib/electric/shape_cache/pure_file_storage/snapshot.ex:91: anonymous fn/1 in Electric.ShapeCache.PureFileStorage.Snapshot.stream_chunk_lines/2
       (elixir 1.18.4) lib/stream.ex:1557: anonymous fn/5 in Stream.resource/3
       (elixir 1.18.4) lib/stream.ex:1066: Stream.do_transform_inner_enum/7
       (elixir 1.18.4) lib/stream.ex:1773: Enumerable.Stream.do_each/4
       (elixir 1.18.4) lib/stream.ex:956: Stream.do_transform/5
       (elixir 1.18.4) lib/stream.ex:1066: Stream.do_transform_inner_enum/7
       (elixir 1.18.4) lib/stream.ex:1773: Enumerable.Stream.do_each/4
       (elixir 1.18.4) lib/stream.ex:956: Stream.do_transform/5
       (elixir 1.18.4) lib/enum.ex:2600: Enum.reduce_while/3
       (electric 1.1.0) lib/electric/shapes/api/response.ex:390: Electric.Shapes.Api.Response.send_stream/2
       (electric 1.1.0) lib/electric/plug/serve_shape_plug.ex:1: Electric.Plug.ServeShapePlug.plug_builder_call/2
       (electric 1.1.0) deps/plug/lib/plug/error_handler.ex:80: Electric.Plug.ServeShapePlug.call/2
       (electric 1.1.0) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in Electric.Plug.Router.dispatch/2
       (telemetry 1.3.0) /home/alco/code/electric-sql/electric/packages/sync-service/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
       (electric 1.1.0) deps/plug/lib/plug/router.ex:242: Electric.Plug.Router.dispatch/2
       (electric 1.1.0) lib/electric/plug/router.ex:1: Electric.Plug.Router.plug_builder_call/2
       test/electric/plug/low_privilege_router_test.exs:75: Electric.Plug.LowPrivilegeRouterTest.get_shape/1
       test/electric/plug/low_privilege_router_test.exs:63: (test)
```

File: packages/sync-service/lib/electric/shapes/consumer/snapshotter.ex [hunk 1]
```diff
@@ -189,23 +189,24 @@ defmodule Electric.Shapes.Consumer.Snapshotter do
...
+            # with querying the database table and writing snapshot data to disk, this function
+            # will be invoked just as the first snapshot chunk is being written to disk. The
+            # consumer process than proceeds with the streaming and will no longer see errors
+            # raised by the snapshot-producing process.
+            #
+            # For correct error handling behaviour in case the snapshot query fails or snapshot
+            # chunks cannot be written to disk, this notifier function is passed down to the
+            # storage implementation so that if an error is raised before it, the consumer
+            # process will see the error and react accordingly.
+            notifier_fn = fn -> GenServer.cast(parent, {:snapshot_started, shape_handle}) end
```
Comment (icehaunter) [inline packages/sync-service/lib/electric/shapes/consumer/snapshotter.ex]: Could you explain this a bit more to me? We're handling all storage failures in the ` def handle_continue(:start_snapshot, state) do` which does a try/rescue and casts a `snapshot_failed` to the parent. This push-down of the notifier makes storage responsibilities and contract a bit more complicated, but I don't see how it makes for better error handling.

**Review by icehaunter — CHANGES_REQUESTED** [review]

File: packages/sync-service/lib/electric/shape_cache/pure_file_storage/snapshot.ex [hunk 2]
```diff
@@ -62,8 +74,20 @@ defmodule Electric.ShapeCache.PureFileStorage.Snapshot do
...
         end
       end,
-      fn {_chunk_num, file, _} ->
-        if file, do: File.close(file)
+      fn
+        {0, nil, {[], 0}} ->
+          # Not a single chunk file has been written. We probably don't have the read
+          # permission on the table, so signal an error.
+          # Doing nothing here is not an option because it would cause the response
+          # streaming process to crash when it doesn't find any snapshot chunk files.
```
Comment (icehaunter) [inline packages/sync-service/lib/electric/shape_cache/pure_file_storage/snapshot.ex]: Also how does this differentiate from an empty result set, or am I missing something?

Comment (alco) [reply packages/sync-service/lib/electric/shape_cache/pure_file_storage/snapshot.ex]: The difference lies in the behavior of `Stream.transform/5`:
- when it reads empty data from the stream, it invokes start_fun, last_fun and after_fun
- when there's an error reading from the stream, only start_fun and after_fun are invoked.

**Comment by alco** [comment]
@icehaunter Great call!

I have rewritten the implementation commit [in place](https://github.com/electric-sql/electric/pull/2947/commits/76f5d1c181d4ec4d92e8f2cb08f094909ca59e75) and added a [new commit](https://github.com/electric-sql/electric/pull/2947/commits/f66646aa1a4b30f103424f39dd7a3bf41026b40c) that shows how the error message is different from the one I was raising explicitly before.

Also rebased the whole branch on top of `main` but that hasn't required any code changes.
