### PR TITLE
fix(electric): Support Prisma shadow database in electric proxy

### LINKED ISSUE #668: Prisma shadow database is incompatible with the electric proxy
I'm struggling to generate new db migrations using prisma.
```
node@da54a5ab2d97 ~/workspace (main) [1]> yarn prisma migrate dev --create-only --schema prisma/electric-proxy/schema.prisma
yarn run v1.22.19
$ /home/node/workspace/node_modules/.bin/prisma migrate dev --create-only --schema prisma/electric-proxy/schema.prisma
Environment variables loaded from .env
Prisma schema loaded from prisma/electric-proxy/schema.prisma
Datasource "db": PostgreSQL database "sheets", schema "public" at "electric:65432"

Error: P3006

Migration `20230923050414_init` failed to apply cleanly to the shadow database. 
Error:
ERROR: Cannot alter column "" of electrified table "public"."Column"
   0: schema_core::state::DevDiagnostic
             at schema-engine/core/src/state.rs:270

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The problem is that the electric proxy thinks that the shadow database is the main database. I'm right now trying to find a workaround for generating migrations.

### PR DESCRIPTION
**Pull request by magnetised**
Fixes #668

### CODE REVIEW

File: components/electric/lib/electric/postgres/proxy/upstream_connection.ex [hunk 1]
```diff
@@ -62,15 +62,22 @@ defmodule Electric.Postgres.Proxy.UpstreamConnection do
...
 
+    Logger.debug("Connecting to upstream server: #{inspect(host)}:#{port}")
+
     {:ok, conn} = :gen_tcp.connect(host, port, [active: true] ++ extra_options, 1000)
     {:noreply, %{state | conn: conn}, {:continue, {:authenticate, params}}}
   end
 
   def handle_continue({:authenticate, params}, state) do
+    user = Map.fetch!(params, :username)
+    database = Map.fetch!(params, :database)
```
Comment (alco) [inline components/electric/lib/electric/postgres/proxy/upstream_connection.ex:73]: When fetching multiple keys from a map like this, it's cleaner to use pattern-matching:
```
%{username: user, database: database} = params
```

**Review by alco — APPROVED** [review]
Brilliant! :sparkles:
