### PR TITLE
fix: ensure correct tagging of live requests in metrics

### LINKED ISSUE #3123: We've stopped emitting live_requests metric
We stopped emitting live requests metric. We should either:
 1. check if current sync_requests tracks sync + live requests
 2. send sync and live request separately
 3. or make sync_requests track sync + live request

### PR DESCRIPTION
**Pull request by icehaunter**
Closes #3123

### CODE REVIEW

File: packages/sync-service/lib/electric/plug/serve_shape_plug.ex [hunk 1]
```diff
@@ -146,6 +145,14 @@ defmodule Electric.Plug.ServeShapePlug do
     conn
   end
 
+  defp get_handle(%{response: %{shape_handle: shape_handle}}), do: shape_handle
+  defp get_handle(%{request: %{shape_handle: shape_handle}}), do: shape_handle
+  defp get_handle(_), do: nil
+
+  defp get_live_mode(%{response: %{params: %{live: live}}}), do: live
+  defp get_live_mode(%{request: %{params: %{live: live}}}), do: live
```
Comment (msfstef) [inline packages/sync-service/lib/electric/plug/serve_shape_plug.ex:153]: if a request comes in as a live request, but we instead do not serve them in live mode, should we mark the request as live in metrics?

**Review by msfstef — APPROVED** [review]

File: packages/sync-service/lib/electric/plug/serve_shape_plug.ex (hunk 1 above)
Comment (icehaunter) [reply packages/sync-service/lib/electric/plug/serve_shape_plug.ex:153]: I think that's OK
