### PR TITLE
fix: ensure graceful crash when `ALTER TABLE` can't take a lock

### LINKED ISSUE #2403: Failure mode: pending transaction blocks replica identity configuration and shape snapshot capture
The setup is simple:
* Prepare the database by running the migration from the react example
* Run Electric
* Open `psql` and start a transaction that inserts into `items`. Do not commit the transaction, leave it hanging.
* Open the react example client to initiate shape creation and watch Electric logs:

```
16:02:25.935 pid=<0.726.0> request_id=GCmhuMSc24HKRDEAAADE [info] GET /v1/shape

16:02:25.998 pid=<0.726.0> request_id=GCmhuMSc24HKRDEAAADE [info] Query String: offset=-1&table=items

16:02:26.061 pid=<0.726.0> request_id=GCmhuMSc24HKRDEAAADE [debug] Table {"public", "items"} found with 1 columns

16:02:26.071 pid=<0.725.0> [debug] Starting consumer for 126949927-1741100546071

16:02:26.153 pid=<0.724.0> [debug] 1 consumers of replication stream

16:02:26.158 pid=<0.725.0> [debug] Returning shape id 126949927-1741100546071 for shape Shape.new!("public.items" [OID 16401])

16:02:26.180 pid=<0.732.0> shape_handle=126949927-1741100546071 [debug] Starting a wait on the snapshot 126949927-1741100546071 for {#PID<0.726.0>, [:alias | #Reference<0.0.92931.2143629266.3116695563.153064>]}}

16:02:26.183 pid=<0.723.0> [info] Altering identity of public.items to FULL

16:02:31.158 pid=<0.734.0> shape_handle=126949927-1741100546071 [error] GenServer {:"Elixir.Electric.ProcessRegistry:single_stack", {Electric.Shapes.Consumer.Snapshotter, "126949927-1741100546071"}} terminating
** (stop) exited in: GenServer.call({:via, Registry, {:"Elixir.Electric.ProcessRegistry:single_stack", {Electric.Replication.PublicationManager, nil}}}, {:add_shape, Shape.new!("public.items" [OID 16401])}, 5000)
    ** (EXIT) time out
    (elixir 1.18.1) lib/gen_server.ex:1128: GenServer.call/3
    (electric 1.0.0-beta.20) lib/electric/replication/publication_manager.ex:101: Electric.Replication.PublicationManager.add_shape/2
    (opentelemetry_api 1.4.0) src/otel_tracer_noop.erl:59: :otel_tracer_noop.with_span/5
    (electric 1.0.0-beta.20) lib/electric/telemetry/open_telemetry.ex:87: anonymous fn/3 in Electric.Telemetry.OpenTelemetry.do_with_span/4
    (telemetry 1.3.0) /home/alco/code/electric-sql/electric/packages/sync-service/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
    (electric 1.0.0-beta.20) lib/electric/shapes/consumer/snapshotter.ex:64: anonymous fn/10 in Electric.Shapes.Consumer.Snapshotter.handle_continue/2
    (opentelemetry_api 1.4.0) src/otel_tracer_noop.erl:59: :otel_tracer_noop.with_span/5
    (electric 1.0.0-beta.20) lib/electric/telemetry/open_telemetry.ex:87: anonymous fn/3 in Electric.Telemetry.OpenTelemetry.do_with_span/4
    (telemetry 1.3.0) /home/alco/code/electric-sql/electric/packages/sync-service/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
    (electric 1.0.0-beta.20) lib/electric/shapes/consumer/snapshotter.ex:58: Electric.Shapes.Consumer.Snapshotter.handle_continue/2
    (stdlib 6.2) gen_server.erl:2335: :gen_server.try_handle_continue/3
    (stdlib 6.2) gen_server.erl:2244: :gen_server.loop/7
    (stdlib 6.2) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
Process Label: {:snapshotter, "126949927-1741100546071"}
Last message: {:continue, :start_snapshot}
State: %{registry: :"Elixir.Registry.ShapeChanges:single_stack", otel_ctx: %{:"$__otel_baggage_ctx_key" => %{"stack_id" => {"single_stack", []}}, {:otel_tracer, :span_ctx} => {:span_ctx, 0, 0, 0, {:tracestate, []}, false, false, false, :undefined}}, shape_handle: "126949927-1741100546071", storage: {Electric.ShapeCache.FileStorage, %Electric.ShapeCache.FileStorage{base_path: "./persistent/shapes/single_stack", shape_handle: "126949927-1741100546071", db: {:via, Registry, {:"Elixir.Electric.ProcessRegistry:single_stack", {Electric.ShapeCache.FileStorage, "126949927-1741100546071"}}}, data_dir: "./persistent/shapes/single_stack/126949927-1741100546071", cubdb_dir: "./persistent/shapes/single_stack/126949927-1741100546071/cubdb", snapshot_dir: "./persistent/shapes/single_stack/126949927-1741100546071/snapshots", log_dir: "./persistent/shapes/single_stack/126949927-1741100546071/log", stack_id: "single_stack", extra_opts: %{}, chunk_bytes_threshold: 25000000, version: 3}}, chunk_bytes_threshold: 25000000, stack_id: "single_stack", publication_manager: {Electric.Replication.PublicationManager, [stack_id: "single_stack"]}, inspector: {Electric.Postgres.Inspector.EtsInspector, [stack_id: "single_stack", server: {:via, Registry, {:"Elixir.Electric.ProcessRegistry:single_stack", {Electric.Postgres.Inspector.EtsInspector, nil}}}]}, log_producer: {:via, Registry, {:"Elixir.Electric.ProcessRegistry:single_stack", {Electric.Replication.ShapeLogCollector, nil}}}, shape_status: {Electric.ShapeCache.ShapeStatus, %Electric.ShapeCache.ShapeStatus{root: "./shape_cache", shape_meta_table: :"single_stack:shape_meta_table", storage: {Electric.ShapeCache.FileStorage, %{chunk_bytes_threshold: 25000000, stack_id: "single_stack", base_path: "./persistent/shapes/single_stack"}}}}, db_pool: {:via, Registry, {:"Elixir.Electric.ProcessRegistry:single_stack", {Electric.DbPool, nil}}}, run_with_conn_fn: &Electric.Shapes.Consumer.Snapshotter.run_with_conn/2, create_snapshot_fn: &Electric.Shapes.Consumer.Snapshotter.query_in_readonly_txn/7, shape: Shape.new!("public.items" [OID 16401])}

16:02:31.191 pid=<0.726.0> request_id=GCmhuMSc24HKRDEAAADE [error] GenServer #PID<0.726.0> terminating
** (stop) exited in: GenServer.call({:via, Registry, {:"Elixir.Electric.ProcessRegistry:single_stack", {Electric.Shapes.Consumer, "126949927-1741100546071"}}}, :await_snapshot_start, 5000)
    ** (EXIT) time out
    (elixir 1.18.1) lib/gen_server.ex:1128: GenServer.call/3
    (electric 1.0.0-beta.20) lib/electric/shapes.ex:20: Electric.Shapes.get_merged_log_stream/3
    (electric 1.0.0-beta.20) lib/electric/shapes/api.ex:475: Electric.Shapes.Api.do_serve_shape_log/1
    (opentelemetry_api 1.4.0) src/otel_tracer_noop.erl:59: :otel_tracer_noop.with_span/5
    (electric 1.0.0-beta.20) lib/electric/telemetry/open_telemetry.ex:87: anonymous fn/3 in Electric.Telemetry.OpenTelemetry.do_with_span/4
    (telemetry 1.3.0) /home/alco/code/electric-sql/electric/packages/sync-service/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
    (electric 1.0.0-beta.20) lib/electric/shapes/api.ex:425: Electric.Shapes.Api.serve_shape_log/2
    (electric 1.0.0-beta.20) lib/electric/plug/serve_shape_plug.ex:1: Electric.Plug.ServeShapePlug.plug_builder_call/2
    (electric 1.0.0-beta.20) deps/plug/lib/plug/error_handler.ex:80: Electric.Plug.ServeShapePlug.call/2
    (electric 1.0.0-beta.20) deps/plug/lib/plug/router.ex:246: anonymous fn/4 in Electric.Plug.Router.dispatch/2
    (telemetry 1.3.0) /home/alco/code/electric-sql/electric/packages/sync-service/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
    (electric 1.0.0-beta.20) deps/plug/lib/plug/router.ex:242: Electric.Plug.Router.dispatch/2
    (electric 1.0.0-beta.20) lib/electric/plug/router.ex:1: Electric.Plug.Router.plug_builder_call/2
    (bandit 1.5.5) lib/bandit/pipeline.ex:124: Bandit.Pipeline.call_plug!/2
    (bandit 1.5.5) lib/bandit/pipeline.ex:36: Bandit.Pipeline.run/4
    (bandit 1.5.5) lib/bandit/http1/handler.ex:12: Bandit.HTTP1.Handler.handle_data/3
    (bandit 1.5.5) lib/bandit/delegating_handler.ex:18: Bandit.DelegatingHandler.handle_data/3
    (bandit 1.5.5) /home/alco/code/electric-sql/electric/packages/sync-service/deps/thousand_island/lib/thousand_island/handler.ex:411: Bandit.DelegatingHandler.handle_continue/2
    (stdlib 6.2) gen_server.erl:2335: :gen_server.try_handle_continue/3
    (stdlib 6.2) gen_server.erl:2244: :gen_server.loop/7
    (stdlib 6.2) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
Process Label: "Request GCmhuMSc24HKRDEAAADE - GET /v1/shape?offset=-1&table=items"
Last message: {:continue, :handle_connection}
State: {%ThousandIsland.Socket{socket: #Port<0.34>, transport_module: ThousandIsland.Transports.TCP, read_timeout: 60000, silent_terminate_on_error: false, span: %ThousandIsland.Telemetry{span_name: :connection, telemetry_span_context: #Reference<0.2143629266.3116630020.153356>, start_time: -576460712712066748, start_metadata: %{remote_port: 40022, remote_address: {127, 0, 0, 1}, telemetry_span_context: #Reference<0.2143629266.3116630020.153356>, parent_telemetry_span_context: #Reference<0.2143629266.3116630020.152787>}}}, %{opts: %{http: [], http_1: [], http_2: [], websocket: []}, plug: {Electric.Plug.Router, [api: %Electric.Shapes.Api{inspector: {Electric.Postgres.Inspector.EtsInspector, [stack_id: "single_stack", server: {:via, Registry, {:"Elixir.Electric.ProcessRegistry:single_stack", {Electric.Postgres.Inspector.EtsInspector, nil}}}]}, pg_id: nil, registry: :"Elixir.Registry.ShapeChanges:single_stack", persistent_kv: %Electric.PersistentKV.Filesystem{root: "./persistent/state"}, shape: nil, shape_cache: {Electric.ShapeCache, [stack_id: "single_stack", server: {:via, Registry, {:"Elixir.Electric.ProcessRegistry:single_stack", {Electric.ShapeCache, nil}}}]}, stack_events_registry: Electric.StackEventsRegistry, stack_id: "single_stack", storage: {Electric.ShapeCache.FileStorage, %{chunk_bytes_threshold: 10485760, stack_id: "single_stack", base_path: "./persistent/shapes/single_stack"}}, allow_shape_deletion: true, long_poll_timeout: 20000, max_age: 1, stack_ready_timeout: 100, stale_age: 3, encoder: Electric.Shapes.Api.Encoder.JSON, configured: true}, publication_manager: {Electric.Replication.PublicationManager, [stack_id: "single_stack", server: {:via, Registry, {:"Elixir.Electric.ProcessRegistry:single_stack", {Electric.Replication.PublicationManager, nil}}}]}, get_service_status: #Function<0.20182840/0 in Electric.StackSupervisor.build_shared_opts/1>]}, handler_module: Bandit.InitialHandler, http_1_enabled: true, http_2_enabled: true}}

16:02:31.299 pid=<0.735.0> request_id=GCmhugZ2UOZCKvYAAAXF [info] GET /v1/shape

16:02:31.300 pid=<0.735.0> request_id=GCmhugZ2UOZCKvYAAAXF [info] Query String: offset=-1&table=items

16:02:31.300 pid=<0.735.0> request_id=GCmhugZ2UOZCKvYAAAXF [debug] Table {"public", "items"} found with 1 columns

16:02:31.300 pid=<0.732.0> shape_handle=126949927-1741100546071 [debug] Starting a wait on the snapshot 126949927-1741100546071 for {#PID<0.735.0>, [:alias | #Reference<0.0.94083.2143629266.3116695557.155331>]}}

16:02:36.303 pid=<0.735.0> request_id=GCmhugZ2UOZCKvYAAAXF [error] GenServer #PID<0.735.0> terminating
** (stop) exited in: GenServer.call({:via, Registry, {:"Elixir.Electric.ProcessRegistry:single_stack", {Electric.Shapes.Consumer, "126949927-1741100546071"}}}, :await_snapshot_start, 5000)
    ** (EXIT) time out
    (elixir 1.18.1) lib/gen_server.ex:1128: GenServer.call/3
    (electric 1.0.0-beta.20) lib/electric/shapes.ex:20: Electric.Shapes.get_merged_log_stream/3
    (electric 1.0.0-beta.20) lib/electric/shapes/api.ex:475: Electric.Shapes.Api.do_serve_shape_log/1
```

The first time around, the publication manager, the snapshotter and the shape consumer processes die. You can see the `[info] Altering identity of public.items to FULL` entry logged prior to that. An empty response is returned to the client and it will send a new request to try and request the shape again.

This time around, only the consumer process dies because it got restarted by the supervisor earlier. There's no more crashing of the publication manager and snapshotter processes, I think because the shape handle already exists. Again, an empty reponse is returned to the client and it will keep trying to GET the shape after a short delay, repeating in a loop.

However, the table's replica identity remains at `default` and no attempt is made to set it to `full` again after the first time the publication manager process crashes.

### PR DESCRIPTION
**Pull request by icehaunter**
"Graceful" here means we return a 500 with a clear error, and next request will succeed if that one can take out a lock. That's instead of crash that leaves the system in unrecoverable state. Closes #2403

### CODE REVIEW

File: packages/sync-service/test/test_helper.exs [hunk 1]
```diff
@@ -4,4 +4,4 @@
 # supervision tree in the test environment.
 # Registry.start_link(name: Electric.Application.process_registry(), keys: :unique)
 
-ExUnit.start(assert_receive_timeout: 400)
+ExUnit.start(assert_receive_timeout: 400, exclude: [slow: true])
```
Comment (alco) [inline packages/sync-service/test/test_helper.exs:7]: If that test is slow because of the 15-second timeout on the genserver call, wouldn't it be better to make the timeout small in the test environment and avoid having a test that takes 15 seconds to run?

Comment (icehaunter) [reply packages/sync-service/test/test_helper.exs:7]: It's actually slow because of a 5s timeout in `PublicationManager.add_shape` and it didn't feel like a good idea to thread through one more timeout for just one test

**Review by alco — APPROVED** [review]
