### PR TITLE
fix: subqueries restoration on startup

### LINKED ISSUE #3261: `Failed to start shape supervisor` when using subqueries
We're running with `allow_subqueries` flag enabled, and we have several shapes that depend on them. When we start a new connection, we face an error, seemingly related to subqueries, and may be related to #3247. 

We're using ECS and EFS (on /mnt/electric).

The error:
```elixir
{{:shutdown,
  {:failed_to_start_child, Electric.ShapeCache.ShapeStatusOwner,
   {{:badkey, 0},
    [
      {:erlang, :map_get, [0, %{}], [error_info: %{module: :erl_erts_errors}]},
      {Electric.Replication.Eval.Parser, :replace_query_parts, 4,
       [file: ~c"lib/electric/replication/eval/parser.ex", line: 1513]},
      {Electric.Replication.Eval.Walker, :accumulating_fold, 5,
       [file: ~c"lib/electric/replication/eval/walker.ex", line: 58]},
      {Electric.Replication.Eval.Walker, :"-process_child_groups/5-fun-0-", 5,
       [file: ~c"lib/electric/replication/eval/walker.ex", line: 140]},
      {Enumerable.List, :reduce, 3, [file: ~c"lib/enum.ex", line: 4964]},
      {Enum, :reduce_while, 3, [file: ~c"lib/enum.ex", line: 2600]},
      {Electric.Replication.Eval.Walker, :accumulating_fold, 5,
       [file: ~c"lib/electric/replication/eval/walker.ex", line: 57]},
      {Electric.Replication.Eval.Walker, :process_children, 6,
       [file: ~c"lib/electric/replication/eval/walker.ex", line: 156]}
    ]}}},
 {:child, :undefined, Electric.Replication.Supervisor,
  {Electric.Replication.Supervisor, :start_link,
   [
     [
       stack_id: "electric-embedded",
       shape_status_owner:
         {Electric.ShapeCache.ShapeStatusOwner,
          [
            stack_id: "electric-embedded",
            shape_status:
              {Electric.ShapeCache.ShapeStatus,
               %Electric.ShapeCache.ShapeStatus{
                 shape_meta_table: :"electric-embedded:shape_meta_table",
                 storage:
                   {Electric.ShapeCache.PureFileStorage,
                    %{
                      tmp_dir: "/mnt/electric/shapes/electric-embedded/.tmp/electric-embedded",
                      chunk_bytes_threshold: 10_485_760,
                      stack_id: "electric-embedded",
                      base_path: "/mnt/electric/shapes/electric-embedded",
                      stack_ets: :"Elixir.Electric.ShapeCache.PureFileStorage:electric-embedded",
                      stack_task_supervisor:
                        {:via, Registry,
                         {:"Electric.ProcessRegistry:electric-embedded",
                          {Electric.ShapeCache.PureFileStorage.TaskSupervisor, nil}}},
                      flush_period: 1000,
                      compaction_config: %{period: 600_000, keep_complete_chunks: 2}
                    }}
               }}
          ]},
       consumer_supervisor:
         {Electric.Shapes.DynamicConsumerSupervisor, [stack_id: "electric-embedded"]},
       shape_cache:
         {Electric.ShapeCache,
          [
            purge_all_shapes?: false,
            stack_id: "electric-embedded",
            storage:
              {Electric.ShapeCache.PureFileStorage,
               %{
                 tmp_dir: "/mnt/electric/shapes/electric-embedded/.tmp/electric-embedded",
                 chunk_bytes_threshold: 10_485_760,
                 stack_id: "electric-embedded",
                 base_path: "/mnt/electric/shapes/electric-embedded",
                 stack_ets: :"Elixir.Electric.ShapeCache.PureFileStorage:electric-embedded",
                 stack_task_supervisor:
                   {:via, Registry,
                    {:"Electric.ProcessRegistry:electric-embedded",
                     {Electric.ShapeCache.PureFileStorage.TaskSupervisor, nil}}},
                 flush_period: 1000,
                 compaction_config: %{period: 600_000, keep_complete_chunks: 2}
               }},
            inspector:
              {Electric.Postgres.Inspector.EtsInspector,
               [
                 stack_id: "electric-embedded",
                 server:
                   {:via, Registry,
                    {:"Electric.ProcessRegistry:electric-embedded",
                     {Electric.Postgres.Inspector.EtsInspector, nil}}}
               ]},
            shape_status:
              {Electric.ShapeCache.ShapeStatus,
               %Electric.ShapeCache.ShapeStatus{
                 shape_meta_table: :"electric-embedded:shape_meta_table",
                 storage:
                   {Electric.ShapeCache.PureFileStorage,
                    %{
                      tmp_dir: "/mnt/electric/shapes/electric-embedded/.tmp/electric-embedded",
                      chunk_bytes_threshold: 10_485_760,
                      stack_id: "electric-embedded",
                      base_path: "/mnt/electric/shapes/electric-embedded",
                      stack_ets: :"Elixir.Electric.ShapeCache.PureFileStorage:electric-embedded",
                      stack_task_supervisor:
                        {:via, Registry,
                         {:"Electric.ProcessRegistry:electric-embedded",
                          {Electric.ShapeCache.PureFileStorage.TaskSupervisor, nil}}},
                      flush_period: 1000,
                      compaction_config: %{period: 600_000, keep_complete_chunks: 2}
                    }}
               }},
            publication_manager:
              {Electric.Replication.PublicationManager, [stack_id: "electric-embedded"]},
            chunk_bytes_threshold: 10_485_760,
            log_producer:
              {:via, Registry,
               {:"Electric.ProcessRegistry:electric-embedded",
                {Electric.Replication.ShapeLogCollector, nil}}},
            consumer_supervisor:
              {:via, Registry,
               {:"Electric.ProcessRegistry:electric-embedded",
                {Electric.Shapes.DynamicConsumerSupervisor, nil}}},
            registry: :"Registry.ShapeChanges:electric-embedded"
          ]},
       publication_manager:
         {Electric.Replication.PublicationManager,
          [
            stack_id: "electric-embedded",
            publication_name: "electric_publication_default",
            can_alter_publication?: true,
            manual_table_publishing?: false,
            db_pool:
              {:via, Registry,
               {:"Electric.ProcessRegistry:electric-embedded", {Electric.DbPool, :admin}}},
            update_debounce_timeout: 0
          ]},
       log_collector:
         {Electric.Replication.ShapeLogCollector,
          [
            stack_id: "electric-embedded",
            inspector:
              {Electric.Postgres.Inspector.EtsInspector,
               [
                 stack_id: "electric-embedded",
                 server:
                   {:via, Registry,
                    {:"Electric.ProcessRegistry:electric-embedded",
                     {Electric.Postgres.Inspector.EtsInspector, nil}}}
               ]},
            persistent_kv: %Electric.PersistentKV.Filesystem{root: "/mnt/electric/state"}
          ]},
       schema_reconciler:
         {Electric.Replication.SchemaReconciler,
          [
            stack_id: "electric-embedded",
            inspector:
              {Electric.Postgres.Inspector.EtsInspector,
               [
                 stack_id: "electric-embedded",
                 server:
                   {:via, Registry,
                    {:"Electric.ProcessRegistry:electric-embedded",
                     {Electric.Postgres.Inspector.EtsInspector, nil}}}
               ]},
            shape_cache: {Electric.ShapeCache, [stack_id: "electric-embedded"]},
            period: 60_000
          ]},
       expiry_manager:
         {Electric.ShapeCache.ExpiryManager,
          [
            max_shapes: nil,
            expiry_ratio: 0.2,
            stack_id: "electric-embedded",
            shape_status:
              {Electric.ShapeCache.ShapeStatus,
               %Electric.ShapeCache.ShapeStatus{
                 shape_meta_table: :"electric-embedded:shape_meta_table",
                 storage:
                   {Electric.ShapeCache.PureFileStorage,
                    %{
                      tmp_dir: "/mnt/electric/shapes/electric-embedded/.tmp/electric-embedded",
                      chunk_bytes_threshold: 10_485_760,
                      stack_id: "electric-embedded",
                      base_path: "/mnt/electric/shapes/electric-embedded",
                      stack_ets: :"Elixir.Electric.ShapeCache.PureFileStorage:electric-embedded",
                      stack_task_supervisor:
                        {:via, Registry,
                         {:"Electric.ProcessRegistry:electric-embedded",
                          {Electric.ShapeCache.PureFileStorage.TaskSupervisor, nil}}},
                      flush_period: 1000,
                      compaction_config: %{period: 600_000, keep_complete_chunks: 2}
                    }}
               }},
            consumer_supervisor:
              {:via, Registry,
               {:"Electric.ProcessRegistry:electric-embedded",
                {Electric.Shapes.DynamicConsumerSupervisor, nil}}}
          ]}
     ]
   ]}, :temporary, true, :infinity, :supervisor, [Electric.Replication.Supervisor]}}
```

### PR DESCRIPTION
**Pull request by icehaunter**
- Fixed JSON deserialization not working at all for shapes with subqueries
- Fixed startup process not restarting materializers for shapes
- Made startup tiered with regards to shape dependency topology

Closes #3261

### CODE REVIEW

File: packages/sync-service/lib/electric/shape_cache.ex [hunk 1]
```diff
@@ -363,6 +351,20 @@ defmodule Electric.ShapeCache do
   end
 
   defp start_shape(shape_handle, shape, state, otel_ctx \\ nil) do
+    Enum.zip(shape.shape_dependencies_handles, shape.shape_dependencies)
+    |> Enum.with_index(fn {shape_handle, inner_shape}, index ->
+      materialized_type =
+        shape.where.used_refs |> Map.fetch!(["$sublink", Integer.to_string(index)])
+
+      ConsumerSupervisor.start_materializer(%{
```
Comment (alco) [inline packages/sync-service/lib/electric/shape_cache.ex:358]: How does this work?

We are starting the materializer child of the ConsumerSupervisor here but the ConsumerSupervisor itself is started below on line 368.

File: packages/sync-service/lib/electric/shape_cache.ex [hunk 2]
```diff
@@ -261,39 +261,40 @@ defmodule Electric.ShapeCache do
...
 
-  defp shape_handles(state) do
-    ShapeStatus.list_shapes(state.stack_id)
-  end
-
   # Timeout is per-shape, not for the entire function
   defp recover_shapes(state, timeout) do
-    all_handles = shape_handles(state)
+    # we're starting here group after group without parallelization between groups
+    all_handles = ShapeStatus.list_shapes(state.stack_id)
```
Comment (alco) [inline packages/sync-service/lib/electric/shape_cache.ex]: The var name no longer corresponds to its value. Same thing inside the `group_into_layers()` function.

File: packages/sync-service/lib/electric/shapes/consumer/materializer.ex [hunk 3]
```diff
@@ -70,6 +70,7 @@ defmodule Electric.Shapes.Consumer.Materializer do
     %{stack_id: stack_id, shape_handle: shape_handle} = opts
 
     Process.set_label({:materializer, shape_handle})
+    Process.flag(:trap_exit, true)
```
Comment (alco) [inline packages/sync-service/lib/electric/shapes/consumer/materializer.ex:73]: Why is this needed? There's a single `handle_info({:EXIT` below and it stops the current process. Which is the default behaviour for linked processes.

File: packages/sync-service/lib/electric/shapes/consumer/materializer.ex [hunk 4]
```diff
@@ -93,6 +94,10 @@ defmodule Electric.Shapes.Consumer.Materializer do
     _ = Consumer.await_snapshot_start(state)
     Consumer.subscribe_materializer(state)
 
+    Process.monitor(GenServer.whereis(Consumer.name(state)),
```
Comment (alco) [inline packages/sync-service/lib/electric/shapes/consumer/materializer.ex:97]: I must be missing something fundamental about materializers because from the code in ShapeCache it seems to me that the materializer process starts before the consumer process.

File: packages/sync-service/lib/electric/shape_cache.ex (hunk 1 above)
Comment (icehaunter) [reply packages/sync-service/lib/electric/shape_cache.ex:358]: We're starting a materializer per inner shape, not for ourselves, and not asserting an ok because if it's been already started for another shape it's ok too

File: packages/sync-service/lib/electric/shape_cache.ex (hunk 2 above)
Comment (icehaunter) [reply packages/sync-service/lib/electric/shape_cache.ex]: This name hasn't corresponded in a while tbh, but good note nonetheless

File: packages/sync-service/lib/electric/shapes/consumer/materializer.ex (hunk 4 above)
Comment (icehaunter) [reply packages/sync-service/lib/electric/shapes/consumer/materializer.ex:97]: Consumer subscribes to a materializer for inner shape. So shapes don't start their own materializers, their dependents ask them to do it

File: packages/sync-service/lib/electric/shapes/consumer/materializer.ex (hunk 3 above)
Comment (icehaunter) [reply packages/sync-service/lib/electric/shapes/consumer/materializer.ex:73]: Without it we've never gotten a "shape consumer down" message that's needed to propagate cleanup (invalidation) to all dependents

Comment (alco) [reply packages/sync-service/lib/electric/shapes/consumer/materializer.ex:73]: How so? The DOWN message sent to the materializer because it monitors the consumer. I don't how trapping exits has anything to do with that.

And if we want to propagate consumer's termination to materializer procesess, we can just use process links, can't we?

**Comment by balegas** [comment]
Next week, would be nice for someone to merge this. It's blocking releasing new cloud dashboard using tanstack db

File: packages/sync-service/lib/electric/shape_cache.ex (hunk 1 above)
Comment (msfstef) [reply packages/sync-service/lib/electric/shape_cache.ex:358]: should we be asserting an `:ok` or `{:error, :already_started}` though? will an actual failure to start the inner shape be handled otherwise?

File: packages/sync-service/lib/electric/shape_cache/shape_status.ex [hunk 5]
```diff
@@ -387,6 +387,24 @@ defmodule Electric.ShapeCache.ShapeStatus do
...
+        handles = Enum.map(deps, &get_existing_shape(meta_table, &1))
+
+        if not Enum.any?(handles, &is_nil/1) do
+          handles = Enum.map(handles, &elem(&1, 0))
+          shape = %Shape{shape | shape_dependencies_handles: handles}
+
+          :ets.update_element(meta_table, {@shape_meta_data, handle}, {2, shape})
+        else
+          Logger.warning("Shape #{inspect(handle)} has dependencies but some are unknown")
+          remove_shape(meta_table, handle)
```
Comment (msfstef) [inline packages/sync-service/lib/electric/shape_cache/shape_status.ex]: Removing this shape here is not removing it from the filesystem, shapes whose dependencies are unknown are never loaded but also never cleaned - which besides leaving trash it also means our current backup integrity checks always fail.

File: packages/sync-service/lib/electric/shape_cache/shape_status.ex [hunk 6]
```diff
@@ -387,6 +387,24 @@ defmodule Electric.ShapeCache.ShapeStatus do
       :ets.insert(meta_table, meta_tuples)
       :ets.insert(last_used_table, last_used_tuples)
 
+      shapes
```
Comment (msfstef) [inline packages/sync-service/lib/electric/shape_cache/shape_status.ex]: nit: could we refactor this into a "restore shape dependencies" function? Or perhaps a `restore_shape_dependencies` for a single shape and run through shapes here, with a comment on why shape dependencies would not be persisted?

File: packages/sync-service/lib/electric/shapes/consumer.ex [hunk 7]
```diff
@@ -83,6 +83,7 @@ defmodule Electric.Shapes.Consumer do
         buffer: [],
         monitors: [],
         cleaned?: false,
+        terminating?: false,
```
Comment (msfstef) [inline packages/sync-service/lib/electric/shapes/consumer.ex:88]: perhaps work for a separate PR, but I've noticed this in other work - once we've marked a consumer as terminating, we should also ignore transactions and other operations as no-ops - currently it keeps writing things but as soon as we `terminate_safely` we've removed the shape from the shape status table so things are in an invalid state

File: packages/sync-service/lib/electric/shapes/consumer/materializer.ex [hunk 8]
```diff
@@ -171,6 +176,22 @@ defmodule Electric.Shapes.Consumer.Materializer do
     {:reply, :ok, %{state | subscribers: MapSet.put(state.subscribers, pid)}}
   end
 
+  def handle_info({:EXIT, _, reason}, state) do
+    {:stop, reason, state}
+  end
+
+  def handle_info({{:consumer_down, _}, _ref, :process, _pid, {:shutdown, :cleanup}}, state) do
+    for pid <- state.subscribers do
+      send(pid, {:materializer_shape_invalidated, state.shape_handle})
```
Comment (msfstef) [inline packages/sync-service/lib/electric/shapes/consumer/materializer.ex:185]: nit: why not make this a `GenServer.cast` (and use a corresponding handler)?

File: packages/sync-service/lib/electric/shapes/shape.ex [hunk 9]
```diff
@@ -101,6 +101,9 @@ defmodule Electric.Shapes.Shape do
      shape.replica}
   end
 
+  def has_dependencies?(%__MODULE__{} = shape), do: shape.shape_dependencies != []
+  def deps_known?(%__MODULE__{} = shape), do: shape.shape_dependencies_handles != []
```
Comment (msfstef) [inline packages/sync-service/lib/electric/shapes/shape.ex]: nit: I encountered this method in the `ShapeStatus` changes and `deps_known?` was hard to understand given we know we have dependencies - something more clear like `dependency_handles_known?` might be more clear?
```suggestion
  def dependency_handles_known?(%__MODULE__{} = shape), do: shape.shape_dependencies_handles != []
```

File: packages/sync-service/lib/electric/shapes/consumer/materializer.ex (hunk 4 above)
Comment (msfstef) [reply packages/sync-service/lib/electric/shapes/consumer/materializer.ex:97]: to help clarify and confirm my own understanding - for each shape, we first start all shapes on which it depends, and for each of those shapes we start their materializer (as they are now shapes that require it given they will act as dependencies to another shape)

The materializer is only ever started _after_ a shape consumer supervisor has started normally, the materializer is added to shapes that have the status of being shape dependencies.

**Review by msfstef — APPROVED** [review]
Looks good, mostly nits 🚀  - just one concern about cleaning up shapes with unknown dependencies during the `ShapeStatus` load procedure

also, worth talking with @magnetised who's doing a lot of work on lazy shape initialisation and this might overlap at this point

File: packages/sync-service/lib/electric/shapes/consumer/materializer.ex (hunk 3 above)
Comment (icehaunter) [reply packages/sync-service/lib/electric/shapes/consumer/materializer.ex:73]: This is about the message arrival order. Without this trap `DOWN` message races with a shutdown request from the supervisor, and doesn't get processed because shutdown request without traps is acted upon immediately

File: packages/sync-service/lib/electric/shape_cache.ex (hunk 1 above)
Comment (icehaunter) [reply packages/sync-service/lib/electric/shape_cache.ex:358]: Yeah, it'll fail to start the dependent shape which is reasonable as we cannot know the correct state at the point and all dependents will die & be invalidated one by one

File: packages/sync-service/lib/electric/shapes/consumer/materializer.ex (hunk 4 above)
Comment (icehaunter) [reply packages/sync-service/lib/electric/shapes/consumer/materializer.ex:97]: Slightly differently - we start all shapes without dependencies, the we're starting all shapes that have dependencies and those dependents ask their dependencies to start the materializer if it's not already started

File: packages/sync-service/lib/electric/shapes/consumer.ex (hunk 7 above)
Comment (icehaunter) [reply packages/sync-service/lib/electric/shapes/consumer.ex:88]: It'll be deleted though, won't it, so writes don't really matter

File: packages/sync-service/lib/electric/shapes/consumer/materializer.ex (hunk 8 above)
Comment (icehaunter) [reply packages/sync-service/lib/electric/shapes/consumer/materializer.ex:185]: No big reason, probably just that I don't like the materializer knowing who's subscribed to it by module name

File: packages/sync-service/lib/electric/shapes/consumer.ex (hunk 7 above)
Comment (msfstef) [reply packages/sync-service/lib/electric/shapes/consumer.ex:88]: they don't but I'm concerned about potential side effects (e.g. we might `notify_new_changes` because of a write after the shape has been removed, which should be fine as the next request will see a 409, I'm just not entirely sure all current and potentially future side effects will behave nicely without a shape status entry)
